services:
  app-service:
    image: ${APP_IMAGE}
    container_name: app-service
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    environment:
      MODEL_HOST: ${MODEL_HOST}
      APP_PORT: ${APP_PORT}
    restart: unless-stopped
    depends_on:
      - model-service

  model-service:
    image: ${MODEL_IMAGE}
    container_name: model-service
    environment:
      MODEL_PORT: ${MODEL_PORT}
      MODEL_URL: ${MODEL_URL}
      DEBUG: ${DEBUG}
    volumes:
      - ./output:/sms/output
    restart: unless-stopped
