services:
  app:
    image: ghcr.io/doda2025-team20/frontend:latest
    container_name: app-service
    ports:
      - "8080:8080"
    environment:
      - MODEL_HOST=http://model-service:8081
    restart:
      unless-stopped

  model-service:
    image: ghcr.io/doda2025-team20/backend:latest
    container_name: model-service
    restart:
      unless-stopped