services:
  app:
    image: ghcr.io/doda2025-team20/frontend:latest
    container_name: app-service
    ports:
      - "8080:8080"
    environment:
      - MODEL_HOST=http://model-service:8081
      # - APP_PORT=8080
    restart:
      unless-stopped

  model-service:
    image: ghcr.io/doda2025-team20/backend:latest
    container_name: model-service
    # environment:
      # - MODEL_PORT=8081
      # - MODEL_URL="" # Source URL for model download
      # - DEBUG=false
    volumes:
      - ./output:/sms/output
    restart:
      unless-stopped