apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config
data:
  APP_ENV: "{{ .Values.app.env | default "production" }}"
  LOG_LEVEL: "{{ .Values.app.logLevel | default "info" }}"
