apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-grafana-datasources
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "myapp.fullname" . }}-prometheus:9090
      isDefault: true
      editable: false