apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-grafana-datasources
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://monitoring-kube-prometheus-prometheus:9090
      isDefault: true
      editable: false