{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-chart.fullname" . }}-grafana
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.grafana.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.grafana.ingress.className }}
  rules:
  - host: {{ .Values.grafana.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "helm-chart.fullname" . }}-grafana
            port:
              number: 3000
{{- end }}