apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sms-traffic-alert
  labels:
    release: monitoring
spec:
  groups:
  - name: sms-app.rules
    rules:
    - alert: HighTrafficDetected
      expr: sum(rate(sms_requests_total[1m])) * 60 > 15 # more than 15 per minute
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: {{ `"High traffic on {{ $labels.instance }}"` | quote }}
        description: {{`"SMS App is receiving {{ $value }} requests per minute."` | quote}}